### ISSUE TITLE
Analyze the nested loop and handle partially equivalent loops.

### ISSUE THREAD

**Issue by KuangjuX** [TiledTensor/ThrillerFlow#10]
The current [`ThrillerBlock`] can generate code based on different nested loops. However, consider a case where in the nested loop scenario, two loop programs may **iterate over the same outer loop variable, but not the inner loop**.

 We should consider how to handle this situation. If not addressed, there may be issues with **invalid references to the outer loop variables** in the subgraphs.

**Comment by KuangjuX** [comment]
I think this seems to require a tree-like data structure, similar to a **B-Tree**, growing downward from the root. The root represents no loops, and each child node represents the addition of one more loop. For example:

```rust
pub struct NestedLoopNode<T> {
    loops: Vec<T>,
    children: Vec<NestedLoop<T>>
}

pub struct NestedLoopTree<T> {
    root: NestedLoopNode<T>,
    height: usize
}
```

**Comment by haruhi55** [comment]
Do you mean by designing a data structure that represents a loop program that looks like this?

```cpp
for (...) {  // parent
  for (...) {
  
    for (...) {  // node1
      for (...) {
        // do something
      }
    }

    for (...) { // node1
      // do somethings
    }

   for (...) {  // node3
      for (...) {
        for (...) {
            // do something
        }

        for (...) {  // node 3-1
            // do something
        }
      }
    }
  }  
}
```
The graphical representation may look like this:

```
       parent
          |
          |
   /-------------\
  /       |       \
node1   node2    node3
                   |
                 node 3-1
```

**Comment by KuangjuX** [comment]
> Do you mean by designing a data structure that represents a loop program that looks like this?
> 
> ```c++
> for (...) {  // root
>   for (...) {
>   
>     for (...) {  // node1, level 1
>       for (...) {
>         // do something
>       }
>     }
> 
>     for (...) { // node2, level 1
>       // do somethings
>     }
> 
>    for (...) {  // node3, level 1
>       for (...) {
>         for (...) {
>             // do something
>         }
> 
>         for (...) {  // node 3-1
>             // do something, level 2
>         }
>       }
>     }
>   }  
> }
> ```
> 
> The graphical representation may look like this:
> 
> ```
>          root
>           |
>           |
>    /-------------\
>   /       |       \
> node1   node2    node3
>                    |
>                  node 3-1
> ```
> 
> each node is a subgraph, and its children can again be a sub-graph.

Yes, that's correct. Therefore, the subgraphs need to be split not only by different memory levels, but also by different nested loops.
